{
    'name': 'Events Portal Session',
    'version': '16.0.0.0.1',
    'category': 'Events',
    'summary': 'List of all events',
    'author': 'Moka Tourisme',
    'description': "List of all events",
    'depends': ['event_portal', 'event_session'],
    'data': [
        'security/account_security.xml',
        'security/ir.model.access.csv',
        'views/event_sessions_portal_templates.xml',
        'views/content_template.xml',
        'views/event_portal_templates.xml',
        'report/session_portal_report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'AGPL-3',
}
